### ISSUE TITLE
Kernel crash while loading driver

### ISSUE THREAD

**Issue by XioNoX** [ulli-kroll/mt7610u#3]
See attached picture.

Env: 
Ubuntu 16.10 64bits, Linux laptop 4.8.0-25-generic #27-Ubuntu SMP Thu Oct 13 03:34:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
current master branch as of a couple hours ago (e33df20)
ID 148f:761a Ralink Technology, Corp.
TP-Link Archer T2UH

STR:
1. git clone
2. make
3. insert dongle
4. sudo insmod mt7610u.ko
After issuing that command, the attached logs gets issued to /var/log/syslog and computer needs a hard reboot.

![dsc_0007](https://cloud.githubusercontent.com/assets/688817/19533743/e2dc296c-95f5-11e6-972f-e40f7b3c42a3.JPG)

let me know how I can troubleshot it more.
Thanks

**Comment by ulli-kroll** [comment]
Hi

upstream has changed API for 
void cfg80211_scan_done(..)
in
1d76250bd34af86c6498fc51e50cab3bfbbeceaa
will fix

another #ifdef mess

**Comment by ulli-kroll** [comment]
fixed in current git.
Tested on APU (x86_64) build with v4.8.3 kernel

If crash exist please provide better log.
The picture is useless, it shows no information about why/which code is damaged.

See this
`fixed in current git.
Tested on APU (x86_64) build with v4.8.3 kernel

If crash exist please provide better log.
The picture is useless, it shows no information about why/which code is damaged.

See this
`[  439.126649] WARNING: CPU: 1 PID: 1080 at net/wireless/sme.c:724 __cfg80211_connect_result+0x2be/0x336
[  439.135871] Modules linked in: mt7610u(O)
[  439.139990] CPU: 1 PID: 1080 Comm: kworker/u4:0 Tainted: G           O    4.8.3 #86
[  439.147651] Hardware name: PC Engines APU, BIOS SageBios_PCEngines_APU-45 04/05/2014
[  439.155394] Workqueue: cfg80211 cfg80211_event_work
[  439.160303]  0000000000000000 ffff880110cefcb0 ffffffff81261ee2 0000000000000000
[  439.167798]  0000000000000000 ffff880110cefcf0 ffffffff810372b3 000002d41a367000
[  439.175298]  ffff880110cc5c00 0000000000000000 ffff88011979d318 0000000000000000
[  439.182794] Call Trace:
[  439.185255]  [<ffffffff81261ee2>] dump_stack+0x4d/0x63
[  439.190402]  [<ffffffff810372b3>] __warn+0xc0/0xdb
[  439.195200]  [<ffffffff8103737b>] warn_slowpath_null+0x18/0x1a
[  439.201034]  [<ffffffff81579846>] __cfg80211_connect_result+0x2be/0x336
[  439.207655]  [<ffffffff8155cc5b>] cfg80211_process_wdev_events+0xdb/0x186
[  439.214452]  [<ffffffff8155cc5b>] ? cfg80211_process_wdev_events+0xdb/0x186
[  439.221419]  [<ffffffff8155cd5a>] cfg80211_process_rdev_events+0x54/0x63
[  439.228125]  [<ffffffff81559071>] cfg80211_event_work+0x19/0x21
[  439.234047]  [<ffffffff81047b20>] process_one_work+0x193/0x2a1
[  439.239889]  [<ffffffff8104816f>] worker_thread+0x279/0x362

[  439.245470]  [<ffffffff81047ef6>] ? rescuer_thread+0x29a/0x29a
[  439.251477]  [<ffffffff8104ba70>] kthread+0xcd/0xd5
[  439.256368]  [<ffffffff815e18ff>] ret_from_fork+0x1f/0x40
udhcpc: started,[  439.261774]  [<ffffffff8104b9a3>] ? kthread_create_on_node+0x177/0x177
 v1.25.1
[  439.269740] ---[ end trace 04df804dd6ccac9e ]---
udhcpc: sending discover
`
This is a slowpath error log, which may be an issue, but currently is not.

**Comment by XioNoX** [comment]
Thanks for your reply, I'm still having the same issue, how can I provide you better logs?
It looks like the kernel crash before being able to display or write to disk the logs.

**Comment by ulli-kroll** [comment]
Hmm,
looking at the log there is some small time delay. only one second.
Can you please disable NetworkManager, I think 
`sudo systemctl stop NetworkManager`
will do this on Ubuntu
load the driver
and enable NetworkManager
`sudo systemctl start NetworkManager`

So it's possible to narrow it down to load module or open Wifi Interface

**Comment by XioNoX** [comment]
Same issue, crashes right after loading the driver.
![More crash logs](https://cloud.githubusercontent.com/assets/688817/19784662/705b1f40-9c4b-11e6-98a1-ce4a38d93eb2.JPG) if it helps.

**Comment by ulli-kroll** [comment]
Sorry for delay, very busy at work last week.

Yeah, better crash log ...

**Comment by thindiyeh** [comment]
same issue

**Comment by ulli-kroll** [comment]
Damn mcu*() functions

**Comment by na-ji** [comment]
In my case, it does not crash when driver is loaded, but when I try to connect to any network. And the kernel crash before writing any log.
